# Generated by Django 4.1.4 on 2023-01-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetinventory',
            unique_together={('ip', 'hostname', 'owner')},
        ),
    ]
